### ISSUE TITLE
Not working with IBM.Data.DB2.iSeries

### ISSUE THREAD

**Issue by arbh89** [martinjw/dbschemareader#27]
I have been trying to use this project with DB2 ISERIES but it is not working.

Running Db2Test i get the next error:

Result Message:	
Test method DatabaseSchemaReaderTest.IntegrationTests.Db2.Db2Test threw exception: 
System.InvalidOperationException: Not enough parameters specified.  The command requires 4 parameter(s), but only 2 parameter(s) exist in the parameter collection.
Result StackTrace:	
at IBM.Data.DB2.iSeries.iDB2Command.openCursor()
   at IBM.Data.DB2.iSeries.iDB2Command.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable[] dataTables, Int32 startRecord, Int32 maxRecords, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable dataTable)
   at DatabaseSchemaReader.ProviderSchemaReaders.Db2ISeriesSchemaReader.IdentityColumns(String tableName, DbConnection connection) in dbschemareader\DatabaseSchemaReader\ProviderSchemaReaders\DbProviders\Db2ISeriesSchemaReader.cs:line 78

**Comment by martinjw** [comment]
Seems to be a known problem with DB2 iseries:
http://stackoverflow.com/questions/24070890/c-sharp-ado-net-ibm-db2-named-parameters-with-same-name-throws-not-enough-parame

Parameter binding fails if named parameter is used more than once (in  this case, there are 2 named parameters, each used twice)

But - it has worked with iSeries before, so it may be different client versions. It may be safer to use positional markers or different names, so we catch all versions. I'll look at this soon...

**Comment by martinjw** [comment]
Can you check with this latest commit?

**Comment by arbh89** [comment]
I am on holidays, i will check when i come back to office.

**Comment by arbh89** [comment]
Hi @martinjw, i have tested the latest commit and now is working but i had to make some changes.

ArgumentsKeyMap.cs
![image](https://cloud.githubusercontent.com/assets/6992258/21824196/e43a137a-d743-11e6-97aa-7c66877fdb1e.png)

StoredProcedureKeyMap.cs
![image](https://cloud.githubusercontent.com/assets/6992258/21824243/10805516-d744-11e6-80d9-dc578408066f.png)

ViewKeyMap.cs
![image](https://cloud.githubusercontent.com/assets/6992258/21824260/2811a996-d744-11e6-9926-6444d78f0853.png)

**Comment by martinjw** [comment]
Thanks- changes added. If you find any other issues, let me know.
