### ISSUE TITLE
Reader v.2.2.0 problem, not read table schema, exception fire

### ISSUE THREAD

**Issue by mutlutan** [martinjw/dbschemareader#31]
//In .net Core, create the connection with the connection string
            using (var connection = new System.Data.SqlClient.SqlConnection("Data Source=.;Integrated Security=true;Initial Catalog=tmy; MultipleActiveResultSets=true;"))
            {
                var dr = new DatabaseSchemaReader.DatabaseReader(connection);
                //Then load the schema (this will take a little time on moderate to large database structures)
                dr.Owner = "dbo";
                var schema = dr.ReadAll();             
            }
---------------------------------
ReadAll error;
+		dr.ReadAll()	'dr.ReadAll()' threw an exception of type 'System.IndexOutOfRangeException'	DatabaseSchemaReader.DataSchema.DatabaseSchema {System.IndexOutOfRangeException}

StacTRACES :
   at System.Data.ProviderBase.BasicFieldNameLookup.GetOrdinal(String fieldName)
   at System.Data.SqlClient.SqlDataReader.GetOrdinal(String name)
   at System.Data.SqlClient.SqlDataReader.get_Item(String name)
   at DatabaseSchemaReader.ProviderSchemaReaders.Converters.RowConverters.ColumnRowConverter.Convert(IDataRecord row)
   at DatabaseSchemaReader.ProviderSchemaReaders.Databases.SqlServer.Columns.Mapper(IDataRecord record)
   at DatabaseSchemaReader.ProviderSchemaReaders.Databases.SqlExecuter.ExecuteDbReader(DbConnection connection)
   at DatabaseSchemaReader.ProviderSchemaReaders.Adapters.SqlServerAdapter.Columns(String tableName)
   at DatabaseSchemaReader.ProviderSchemaReaders.Builders.TableBuilder.Execute(CancellationToken ct)
   at DatabaseSchemaReader.DatabaseReader.AllTables(CancellationToken ct)
   at DatabaseSchemaReader.DatabaseReader.ReadAll(CancellationToken ct)

**Comment by martinjw** [comment]
Not sure why it can't read a fieldname here. I test against .NetCore.App 1.0.1 and the latest VS2017 RC , and it's fine, but perhaps it's some variation in platform or target framework where field names are case sensitive or something... 

I quickly refactored the columns reading to simplify it... here's the latest build if you'd like to try.
https://github.com/martinjw/dbschemareader/releases/tag/2.3.0.16

**Comment by mutlutan** [comment]
Problem solved, thank you.
Many thanks also to this library...
